leader/urls.py
from django.urls import path
from leader import views

app_name = 'leader'
urlpatterns = [
    path('dashboard/', views.LeaderDashboardAPIView.as_view(), name='leader_dashboard'),
    path('dashboard/worker/', views.WorkerListTemplateAPIView.as_view(), name='leader_worker'),
    path('dashboard/project/', views.ProjectListTemplateAPIView.as_view(), name='leader_project'),
    path('dashboard/project/<str:pk>/', views.ProjectDetailTemplateAPIView.as_view(), name='leader_project_detail'),
    path('dashboard/project/add/new/', views.ProjectCreateTemplateAPIView.as_view(), name='leader_project_add'),
    path('dashboard/project/submited/list/', views.SubmitedProjectsTemplateAPIView.as_view(), name='leader_project_submission'),
    path('dashboard/task/', views.TaskListTemplateAPIView.as_view(), name='leader_task'),
    path('dashboard/notification/send/', views.SendNotificationTemplateView.as_view(), name='leader_send_notification'),
]

payments/urls.py
from django.urls import path
from payments import views

app_name = "payments"
urlpatterns = [
    path('worker/', views.PaymentProjectBasedTemplateView.as_view(), name='payment_project_based'),
    path('send/worker/', views.PaymentWorkerTemplateView.as_view(), name='payment_worker'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main/admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('leader/', include('leader.urls', namespace='leader')),
    path('worker/', include('worker.urls', namespace='worker')),
    path('admin/', include('admin_dashboard.urls', namespace='admin_dashboard')),
    path('payments/', include('payments.urls', namespace='payments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

payments/models.py
from django.db import models
from accounts.models import User
from projects.models import Project
from django.db.models import Q
import datetime

# Payment model
class Payments(models.Model):
    project = models.ForeignKey(Project, on_delete=models.CASCADE, related_name='payments', blank=False, null=False)
    sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='leader_payments', blank=False, null=False)
    receivers = models.ManyToManyField(User, related_name='worker_payments', blank=False)
    amount = models.FloatField(default=0, blank=False, null=False)
    per_entry = models.FloatField(default=0, blank=True, null=True)
    salary = models.FloatField(default=0, blank=True, null=True)
    is_received = models.BooleanField(default=False)
    is_accept = models.BooleanField(default=False)
    date = models.DateField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self) -> str:
        return f"Payment to {self.project}"
    
    class Meta:
        verbose_name_plural = 'Payments Employee'

    def entry_totals(self):
        totals = 0
        for entry in self.project.issues.all():
            totals += int(entry.total_data_entry_today)
        return totals*self.per_entry

    def total_entry_amount(self, user):
        total_per_entry = 0
        total_entry = 0
        payment_obj = Payments.objects.filter(Q(receivers=user) & Q(project__worker=user) & Q(project__status='done', is_received=True))
        for project in payment_obj:
            total_per_entry += project.per_entry
            for issues in project.project.issues.all():
                if int(issues.total_data_entry_today) == 0:
                    pass
                else:
                    total_entry += int(issues.total_data_entry_today)
            
        return total_entry*total_per_entry
    
    # today earning
    def today_earning(self, user):
        # today earning
        today = datetime.date.today()
        today_earning_obj = Payments.objects.filter(Q(date=today) & Q(receivers=user) & Q(project__worker=user) & Q(project__status='done', is_received=True))
        today_earning = 0
        if today_earning_obj.exists():
            for today_earn in today_earning_obj:
                today_earning += today_earn.amount
            return today_earning + self.total_entry_amount(user)
        else:
            return today_earning

    # this week earning
    def week_earning(self, user):
        # this week earning
        week_start = datetime.date.today()
        week_start -= datetime.timedelta(days=week_start.weekday())
        week_end = week_start + datetime.timedelta(days=7)
        this_week_earning_obj = Payments.objects.filter(Q(date__gte=week_start, date__lt=week_end) & Q(receivers=user) & Q(project__worker=user) & Q(project__status='done', is_received=True, is_accept=True))
        if this_week_earning_obj.exists():
            week_earning = 0
            for week_earn in this_week_earning_obj:
                week_earning += week_earn.amount
            return week_earning + self.total_entry_amount(user)
        else:
            return 0

    # this month earning
    def month_earning(self, user):
        # this month earning
        this_month_earning_obj = Payments.objects.filter(Q(date__gte=datetime.datetime.today().replace(day=1, hour=0, minute=0, second=0, microsecond=0)) & Q(receivers=user) & Q(project__worker=user) & Q(project__status='done', is_received=True, is_accept=True))
        if this_month_earning_obj.exists():
            month_earning = 0
            for month_earn in this_month_earning_obj:
                month_earning += month_earn.amount
            return month_earning + self.total_entry_amount(user)
        else:
            return 0

    # this year earning
    def year_earning(self, user):
        # this year earning
        this_year_earning_obj = Payments.objects.filter(Q(date__year=datetime.datetime.now().year) & Q(receivers=user) & Q(project__worker=user) & Q(project__status='done', is_received=True, is_accept=True))
        if this_year_earning_obj.exists():
            year_earning = 0
            for year_earn in this_year_earning_obj:
                year_earning += year_earn.amount
            return year_earning + self.total_entry_amount(user)
        else:
            return 0
    
    # current user totals earnings
    def totals_earning(self, user):
        totals_earning_obj = Payments.objects.filter(Q(project__status='done') & Q(receivers=user) & Q(project__worker=user) & Q(is_received=True, is_accept=True))
        if totals_earning_obj.exists():
            totals_earning = 0
            for worker in totals_earning_obj:
                totals_earning += worker.amount
            return totals_earning + self.total_entry_amount(user)
        else:
            return 0

payments/forms.py
from django import forms
from django.contrib.auth import get_user_model
from projects.models import Project
from payments.models import Payments
User = get_user_model()

# pay project based form
class PaymentsProjectForm(forms.ModelForm):
    receivers = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(user_type='worker'),
        widget=forms.CheckboxSelectMultiple
    )
    class Meta:
        model = Payments
        fields = [
            'amount',
            'per_entry',
            'receivers',
        ]
        widgets = {
            'amount': forms.NumberInput(attrs={'class': 'form-control'}), 
            'per_entry': forms.NumberInput(attrs={'class': 'form-control'}), 
        }


# pay to direct worker form
class PaymentWorkerForm(forms.ModelForm):
    receivers = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(user_type='worker'),
        widget=forms.CheckboxSelectMultiple
    )

    class Meta:
        model = Payments
        fields = [
            'project',
            'amount',
            'per_entry',
            'receivers',
        ]
        widgets = {
            'project': forms.Select(attrs={'class': 'form-control'}), 
            'amount': forms.NumberInput(attrs={'class': 'form-control'}), 
            'per_entry': forms.NumberInput(attrs={'class': 'form-control'}), 
        }

payments/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from accounts.models import User, Notification
from payments.forms import PaymentsProjectForm, PaymentWorkerForm
from payments.models import Payments
from projects.models import Project
import datetime
from django.contrib import messages


# payment worker creation view
class PaymentProjectBasedTemplateView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # redirect to user dashboard
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            elif request.user.user_type == 'leader':
                # project_id = request.GET.get('pay_for')
                # project_obj = Project.objects.get(id=project_id)
                # workers = project_obj.worker.all()

                form = PaymentsProjectForm()
                context = {
                    'form': form
                }
                return render(request, 'payments/payment_project_based.html', context)
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'post' or request.method == 'POST':
                # here will execute tasks
                project_id = request.GET.get('pay_for')
                project_obj = Project.objects.get(id=project_id)
                form = PaymentsProjectForm(request.POST, request.FILES)
                if form.is_valid():
                    instance = form.save(commit=False)
                    instance.project = project_obj
                    instance.sender = request.user
                    instance.date = datetime.date.today()
                    instance.save()
                    for worker in request.POST.getlist('receivers'):
                        instance.receivers.add(worker)
                    messages.success(request, "Payment has been sended!")
                    notification_obj = Notification.objects.create(from_leader=request.user, subject="Payments Info", is_active=True, message="Congratulation! you have a new payments let confirm it.")
                    for to_worker in request.POST.getlist('receivers'):
                        notification_obj.to_worker.add(to_worker)
                        notification_obj.save()
                    return redirect('leader:leader_project')
                else:
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER')) # return the same page if run this (else) conditon

        else:
            return redirect('accounts:login')



# payment worker creation view
class PaymentWorkerTemplateView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # redirect to user dashboard
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            elif request.user.user_type == 'leader':
                form = PaymentWorkerForm()
                context = {
                    'form': form
                }
                return render(request, 'payments/payment_worker.html', context)
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'post' or request.method == 'POST':
                # here will execute tasks
                form = PaymentWorkerForm(request.POST, request.FILES)
                if form.is_valid():
                    instance = form.save(commit=False)
                    instance.sender = request.user
                    instance.is_received = True
                    instance.is_accept = True
                    instance.date = datetime.date.today()
                    instance.save()
                    for worker in request.POST.getlist('receivers'):
                        instance.receivers.add(worker)
                    messages.success(request, "Payment submited successfully..!")
                    notification_obj = Notification.objects.create(from_leader=request.user, subject="Payments Info", is_active=True, message="Congratulation! you have a new payments let confirm it.")
                    for to_worker in request.POST.getlist('receivers'):
                        notification_obj.to_worker.add(to_worker)
                        notification_obj.save()
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                else:
                    messages.warning(request, "Failed payment request try again..!")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER')) # return the same page if run this (else) conditon

        else:
            return redirect('accounts:login')

payments/templates/payments/payment_project_based.html
{% extends 'base.html' %}
{% block title %}Payment Workers Project Based{% endblock title %}
{% block body %}
<!-- Page Body Start-->
<div class="page-body-wrapper default-menu default-menu">
  <!-- Page Sidebar Start-->

  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>
               Payment to workers</h3>
          </div>

          <div class="col-12 col-sm-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'leader:leader_dashboard' %}">                                       <i data-feather="home"></i></a></li>
              <li class="breadcrumb-item">Payment</li>
              <li class="breadcrumb-item active">Workers                           </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <form method='POST' enctype='multipart/form-data'>
                {% csrf_token %}

                <div class="form theme-form projectcreate">
                  <div class="row">
                    <div class="col-6">
                      <div class="mb-3">
                        <label>Pay For Full Project</label>
                        {{form.amount}}
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="mb-3">
                        <label>Pay Per Entry</label>
                        {{form.per_entry}}
                      </div>
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="mb-3">
                        <label>Workers</label>
                        {{form.receivers}}
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="text-end"><button type='submit' class="btn btn-secondary me-3">Add Project</button><a class="btn btn-danger" href="{% url 'leader:leader_project' %}">Cancel</a></div>
                    </div>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid Ends-->



  </div>
</div>
{% endblock body %}
    

payments/templates/payments/payment_worker.html
{% extends 'base.html' %}
{% block title %}Payments To Workers{% endblock title %}
{% block body %}
<!-- Page Body Start-->
<div class="page-body-wrapper default-menu default-menu">
  <!-- Page Sidebar Start-->

  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>
               Payment to workers</h3>
          </div>

          <div class="col-12 col-sm-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'leader:leader_dashboard' %}">                                       <i data-feather="home"></i></a></li>
              <li class="breadcrumb-item">Payment</li>
              <li class="breadcrumb-item active">Workers                           </li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="row">
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <form method='POST' enctype='multipart/form-data'>
                {% csrf_token %}

                <div class="form theme-form projectcreate">
                  <div class="row">
                    <div class="col-12">
                      <div class="mb-3">
                        <label>Project On</label>
                        {{form.project}}
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col-6">
                      <div class="mb-3">
                        <label>Pay for full project</label>
                        {{form.amount}}
                      </div>
                    </div>
                    <div class="col-6">
                      <div class="mb-3">
                        <label>Pay per entry</label>
                        {{form.per_entry}}
                      </div>
                    </div>
                  </div>
                  
                  <div class="row">
                    <div class="col-sm-12">
                      <div class="mb-3">
                        <label>Workers</label>
                        {{form.receivers}}
                      </div>
                    </div>
                  </div>

                  <div class="row">
                    <div class="col">
                      <div class="text-end"><button type='submit' class="btn btn-secondary me-3">Submit Payments</button><a class="btn btn-danger" href="{% url 'leader:leader_project' %}">Cancel</a></div>
                    </div>
                  </div>
                </div>

              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid Ends-->



  </div>
</div>
{% endblock body %}
    