leader/urls.py
from django.urls import path
from leader import views

app_name = 'leader'
urlpatterns = [
    path('dashboard/', views.LeaderDashboardAPIView.as_view(), name='leader_dashboard'),
    path('dashboard/worker/', views.WorkerListTemplateAPIView.as_view(), name='leader_worker'),
    path('dashboard/project/', views.ProjectListTemplateAPIView.as_view(), name='leader_project'),
    path('dashboard/project/<str:pk>/', views.ProjectDetailTemplateAPIView.as_view(), name='leader_project_detail'),
    path('dashboard/project/add/new/', views.ProjectCreateTemplateAPIView.as_view(), name='leader_project_add'),
    path('dashboard/project/submited/list/', views.SubmitedProjectsTemplateAPIView.as_view(), name='leader_project_submission'),
    path('dashboard/task/', views.TaskListTemplateAPIView.as_view(), name='leader_task'),
    path('dashboard/notification/send/', views.SendNotificationTemplateView.as_view(), name='leader_send_notification'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main/admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('leader/', include('leader.urls', namespace='leader')),
    path('worker/', include('worker.urls', namespace='worker')),
    path('admin/', include('admin_dashboard.urls', namespace='admin_dashboard')),
    path('payments/', include('payments.urls', namespace='payments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

worker/urls.py
import imp
from django.urls import path
from worker import views

app_name = 'worker'

urlpatterns = [
    path('dashboard/', views.WorkerDashboardTemplateAPIView.as_view(), name='worker_dashboard'),
    path('dashboard/project/', views.ProjectListTemplateView.as_view(), name='worker_project'),
    path('dashboard/project/<str:pk>/', views.ProjectDetailTemplateView.as_view(), name='worker_project_detail'),
    path('dashboard/task/', views.TaskListTemplateView.as_view(), name='worker_task'),
    path('dashboard/project/submited/list/', views.SubmitedProjectsTemplateView.as_view(), name='worker_project_submited'),
    path('dashboard/project/payment/accept/<str:pk>/', views.AcceptProjectTemplateView.as_view(), name='worker_project_accept'),
    path('dashboard/payments/info/', views.MyPaymentsTemplateView.as_view(), name='worker_my_payment'),
]

projects/forms.py
from django import forms
from projects.models import Categories, Project, Task, Issues, ProjectSubmission
from django.contrib.auth import get_user_model

User = get_user_model()

class ProjectModelForm(forms.ModelForm):
    worker = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(user_type='worker'),
        widget=forms.CheckboxSelectMultiple
    )
    class Meta:
        model = Project
        fields = [
            'name',
            'category',
            'worker',
            'status',
            'work_start_date',
            'work_end_date',
            'deadline',
            'project_client_budget',
            'project_eastemate_cost',
            'sort_description',
            'description',
            'complete_per',
            'file',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Project name *'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'work_start_date': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en'}),
            'work_end_date': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en'}),
            'deadline': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en'}),
            'project_client_budget': forms.NumberInput(attrs={'class': 'form-control'}),
            'project_eastemate_cost': forms.NumberInput(attrs={'class': 'form-control'}),
            'sort_description': forms.TextInput(attrs={'class': 'form-control', 'id': 'exampleFormControlTextarea4', 'rows':'3'}),
            
        }


class TaskModelForm(forms.ModelForm):
    worker = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(user_type='worker'),
        widget=forms.CheckboxSelectMultiple
    )
    class Meta:
        model = Task
        fields = [
            'name',
            'project',
            'worker',
            'status',
            'due',
            'deadline',
            'is_active',
            'complete_per',
            'description',
            'file'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'project': forms.Select(attrs={'class': 'form-select'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'due': forms.Select(attrs={'class': 'form-select'}),
            'deadline': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en', 'placeholder': 'Date'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'checkbox_animated', 'type': 'checkbox'}),
            'complete_per': forms.TextInput(attrs={'class': 'form-control'})
            
        }


# Project submission 
class ProjectSubmissionModelForm(forms.ModelForm):
    class Meta:
        model = ProjectSubmission
        fields = ['project', 'description', 'file']


class IssuesModelForm(forms.ModelForm):
    class Meta:
        model = Issues
        fields = [
            'status',
            'due',
            'today_start_work',
            'today_end_work',
            'total_data_entry_today',
            'complete_per',
            'file'
        ]
        widgets = {
            'status': forms.Select(attrs={'class': 'form-select'}),
            'due': forms.Select(attrs={'class': 'form-select'}),
            'today_start_work': forms.TimeInput(attrs={'class': 'form-select', 'type':'time'}),
            'today_end_work': forms.TimeInput(attrs={'class': 'form-select', 'type':'time'}),
            'total_data_entry_today': forms.TextInput(attrs={'class': 'form-control'}),
            'complete_per': forms.NumberInput(attrs={'class': 'form-control'})
            
        }

projects/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

worker/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render

from django.views.generic import TemplateView
from projects.forms import IssuesModelForm, ProjectSubmissionModelForm, TaskModelForm
from projects.models import Issues, Project, ProjectSubmission, Task
from django.db.models import Q
from django.contrib import messages
from payments.models import Payments
import datetime


class WorkerDashboardTemplateAPIView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            elif request.user.user_type == 'leader':
                return redirect('leader:leader_dashboard')
            elif request.user.user_type == 'worker':
                if request.user.profile.is_fully_filled():
                    # project filtering object
                    worker_project_obj = Project.objects.filter(worker=request.user).first()
                    # project filtering object

                    # tasks and issues filtering
                    worker_task = Task.objects.filter(Q(worker=request.user) & Q(status='done'))
                    worker_issues = Issues.objects.filter(Q(project__worker=request.user))
                    # tasks and issues filtering

                    # project submited filtering object
                    project_submited_obj = ProjectSubmission.objects.filter(Q(project__worker=request.user, status='done') & Q(project__status='done'))
                    # project submited filtering object
                    # earning filtering here ===============
                    payment_worker_obj = Payments.objects.filter(receivers=request.user)
                    # earning filtering here ================
                    if payment_worker_obj.exists():
                        get_worker_earnings = payment_worker_obj.first()
                        context = {
                            'total_project_accept': worker_project_obj.project_accept(request.user),
                            'total_project_pending': worker_project_obj.project_pending(request.user),
                            'total_project_decline': worker_project_obj.project_decline(request.user),
                            'total_project_submited': project_submited_obj,
                            'worker_task': worker_task,
                            'worker_issues': worker_issues,
                            'totals_earning': get_worker_earnings.totals_earning(request.user),
                            'today_earning': get_worker_earnings.today_earning(request.user),
                            'week_earning': get_worker_earnings.week_earning(request.user),
                            'month_earning': get_worker_earnings.month_earning(request.user),
                            'year_earning': get_worker_earnings.year_earning(request.user)
                        }
                        messages.info(request, f"Hello '{request.user}' Welcome back to your dashboard..!")
                        return render(request, 'worker/index.html', context)
                    else:
                        context = {
                            'total_project_accept': 0,
                            'total_project_pending': 0,
                            'total_project_decline': 0,
                            'total_project_submited': 0,
                            'worker_task': worker_task,
                            'worker_issues': worker_issues,
                            'totals_earning': 0,
                            'today_earning': 0,
                            'week_earning': 0,
                            'month_earning': 0,
                            'year_earning': 0
                        }
                        messages.info(request, f"Hello '{request.user}' Welcome back to your dashboard..!")
                        return render(request, 'worker/index.html', context)
                else:
                    return redirect('accounts:accounts_edit_profile')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        pass

# project List view
class ProjectListTemplateView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.profile.is_fully_filled():
                # redirect to user dashboard
                if request.user.user_type == 'admin':
                    return redirect('admin_dashboard:admin_dashboard')
                elif request.user.user_type == 'leader':
                    return redirect('leader:leader_dashboard')
                elif request.user.user_type == 'worker':
                    projects = Project.objects.filter(Q(worker = request.user) & Q(is_active = True)).order_by('-id')
                    context = {
                        'projects': projects
                    }
                    return render(request, 'worker/projects.html', context)
                else:
                    return redirect('accounts:login')
            else:
                return redirect('accounts:accounts_edit_profile')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        pass

# project detials view
class ProjectDetailTemplateView(TemplateView):
    def get(self, request, pk, *args, **kwargs):
        if request.user.is_authenticated:
            if request.user.profile.is_fully_filled():
                # redirect to user dashboard
                if request.user.user_type == 'admin':
                    return redirect('admin_dashboard:admin_dashboard')
                elif request.user.user_type == 'leader':
                    return redirect('leader:leader_dashboard')
                elif request.user.user_type == 'worker':
                    project = Project.objects.get(id=pk)
                    tasks = Task.objects.filter(project=project).order_by('-id')

                    form = ProjectSubmissionModelForm()
                    issues_form = IssuesModelForm()
                    
                    context = {
                        'project': project,
                        'tasks': tasks,
                        'form': form,
                        'issues_form': issues_form
                    }
                    return render(request, 'worker/project_detail.html', context)
                else:
                    return redirect('accounts:login')
            else:
                return redirect('accounts:accounts_edit_profile')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'post' or request.method == 'POST':
                # here will execude tasks
                project_id = request.POST.get('project_id')
                project_obj = Project.objects.get(id=project_id)
                postData = {
                    'project': project_obj,
                    'description': request.POST.get('description'),
                    'file': request.POST.get('file')
                }
                form = ProjectSubmissionModelForm(postData, request.FILES)
                # Issues form submission ======================================
                issues_form = IssuesModelForm(request.POST, request.FILES)

                # Project form submission ======================================
                if form.is_valid():
                    if ProjectSubmission.objects.filter(project=project_id).exists():
                        messages.info(request, "This Project Has Been Submited..!")
                        return redirect('worker:worker_project')
                    else:
                        instance = form.save(commit=False)
                        instance.user = request.user
                        instance.status = 'done'
                        instance.save()
                        ## here will update all {project, task} status to DONE becouse project is submited
                        project_obj.status = 'done'
                        project_obj.complete_per = 100
                        for task in project_obj.tasks.all():
                            task.status = 'done'
                            task.due = 'done'
                            task.save()
                        project_obj.save()
                        ## end updated all info
                        # update payments info
                        if Payments.objects.filter(receivers=request.user, project=project_obj).exists():
                            payment_obj = Payments.objects.filter(receivers=request.user, project=project_obj).first()
                            payment_obj.is_received = True
                            payment_obj.is_accept = True
                            payment_obj.save()
                        # update payments info

                        messages.info(request, "'Congratulations!' Project Successfully Submited..!")
                        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

                # Issues form submission ======================================
                if issues_form.is_valid():
                    instance = issues_form.save(commit=False)
                    instance.user = request.user
                    instance.project = project_obj
                    instance.task = None
                    instance.is_active = True
                    instance.save()
                    messages.info(request, "Issues Successfully..!")
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                else:
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
            else:

worker/templates/worker/my_payments.html
{% extends "base.html" %}
{% block title %}Transaction Of: {{request.user.profile.full_name}}{% endblock title %}
{% load project_data_entry %}

{% block body %}

<!-- Page Body Start-->
<div class="page-body-wrapper">
  <!-- Page Sidebar Start-->

  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>Payment Transactions</h3>
          </div>
          <div class="col-12 col-sm-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="{% url 'worker:worker_dashboard' %}">                                       <i data-feather="home"></i></a></li>
              <li class="breadcrumb-item">payments</li>
              <li class="breadcrumb-item active">my</li>
              <li class="breadcrumb-item active">transaction</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="display" id="advance-1">
                  <thead>
                    <tr>
                      <th>Project</th>
                      <th>Salary</th>
                      <th>Amount</th>
                      <th>Per Entry</th>
                      <th>Entry Amount</th>
                      <th>Received</th>
                      <th>Dates</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for payment in my_payments %}
                      <tr>
                        <td style="font-weight: bold;">{{payment.project.name}}</td>
                        <td style="color:green;font-weight: bold;">{{payment.salary}}</td>
                        <td style="color:green;font-weight: bold;">{{payment.amount}}</td>
                        <td style="color:green;font-weight: bold;">{{payment.per_entry}}</td>
                        <td style="color:green;font-weight: bold;">{{payment.entry_totals}}</td>
                        <td>{{payment.is_received}}</td>
                        <td>{{payment.date}}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
    <!-- Container-fluid Ends-->
  </div>
</div>

{% endblock body %}
    

worker/templates/worker/project_submission.html
{% extends "base.html" %}
{% block title %}Projects Submited By: {{request.user.profile.full_name}}{% endblock title %}
{% load project_data_entry %}

{% block body %}

<!-- Page Body Start-->
<div class="page-body-wrapper">
  <!-- Page Sidebar Start-->

  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>Submited Projects</h3>
          </div>
          <div class="col-12 col-sm-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">                                       <i data-feather="home"></i></a></li>
              <li class="breadcrumb-item">project</li>
              <li class="breadcrumb-item active">submited</li>
              <li class="breadcrumb-item active">list</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="display" id="advance-1">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Status</th>
                      <th>Data Entry</th>
                      <th>Start Work</th>
                      <th>End Work</th>
                      <th>Budget</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for project in submited_projects %}
                      <tr>
                        <td>{{project.project.name}}</td>
                        <td>{{project.project.status}}</td>
                        <td>{{project.project | total_data_entry}}</td>
                        <td>{{project.project.work_start_date}}</td>
                        <td>{{project.project.work_end_date}}</td>
                        <td>{{project.project.project_client_budget}}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
    <!-- Container-fluid Ends-->
  </div>
</div>

{% endblock body %}
    

worker/templates/worker/tasks.html
{% extends "base.html" %}
{% block title %}Tasks and Issues Board{% endblock title %}
{% block body %}

<!-- Page Body Start-->
<div class="page-body-wrapper">
  <!-- Page Sidebar Start-->
  
  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>Tasks</h3>
          </div>
          <div class="col-12 col-sm-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">                                       <i data-feather="home"></i></a></li>
              <li class="breadcrumb-item">Apps</li>
              <li class="breadcrumb-item active">Task</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="email-wrap bookmark-wrap">
        <div class="row">
          <div class="col-xl-3 box-col-3 xl-30">
            <div class="email-sidebar"><a class="btn btn-primary email-aside-toggle" href="javascript:void(0)">bookmark filter</a>
              <div class="email-left-aside">
                <div class="card">
                  <div class="card-body">
                    <div class="email-app-sidebar left-bookmark">
                      <div class="media">
                        <div class="media-size-email"><img style="width:60px; height:60px" class="me-3 rounded-circle" src="{{request.user.profile.employe_image.url}}" alt=""></div>
                        <div class="media-body">
                          <h6 class="f-w-600">{{request.user.profile.full_name}}</h6>
                          <p>{{request.user.email}}</p>
                        </div>
                      </div>
                      <ul class="nav main-menu custom-scrollbar" role="tablist">

                        <li class="nav-item"><span class="main-title"> Functions </span></li>
                        <li><a id="pills-created-tab" data-bs-toggle="pill" href="#pills-created" role="tab" aria-controls="pills-created" aria-selected="true"><span class="title"> Tasks List </span></a></li>
                        <li><a class="show" id="pills-assigned-tab" data-bs-toggle="pill" href="#pills-assigned" role="tab" aria-controls="pills-assigned" aria-selected="false"><span class="title">Issues List</span></a></li>
                        
                      </ul>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div class="col-xl-9 box-col-9 col-md-12 xl-70">
            <div class="email-right-aside bookmark-tabcontent">
              <div class="card email-body radius-left">
                <div class="ps-0">
                  <div class="tab-content">


                    <div class="tab-pane fade active show" id="pills-created" role="tabpanel" aria-labelledby="pills-created-tab">
                      <div class="card mb-0">
                        <div class="card-header d-flex">
                          <h5 class="mb-0">Task List</h5><a href="#"><i class="me-2" data-feather="printer"></i>Print</a>
                        </div>
                        <div class="card-body p-0">
                          <div class="taskadd">
                            <div class="table-responsive">
                              <table class="table">
                                {% for task in tasks %}
                                  <tr>
                                    <td>
                                      <h6 class="task_title_0">{{task.name}}</h6>
                                      <p class="project_name_0">{{task.project.name}}</p>
                                    </td>
                                    <td>
                                      <p class="task_desc_0">{{task.description.html|safe|truncatechars:25}}</p>
                                    </td>
                                    
                                    <td>
                                      <a href="javascript:void(0)"><i data-feather="edit-3"></i></a>
                                      
                                      <a class="pl-2" href="javascript:void(0)"><i data-feather="trash-2"></i></a>
                                    </td>
                                    
                                    
                                  </tr>
                                {% endfor %}
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    
                    <div class="fade tab-pane" id="pills-assigned" role="tabpanel" aria-labelledby="pills-assigned-tab">
                      <div class="card mb-0">
                        <div class="card-header d-flex">
                          <h6 class="mb-0">Issues List</h6><a href="javascript:void(0)"><i class="me-2" data-feather="printer"></i>Print</a>
                        </div>
                        <div class="card-body p-0">
                          <div class="taskadd">
                            <div class="table-responsive" style="padding:20px">
                              <table class="display" id="advance-1">
                                <thead>
                                  <tr>
                                    <th>Project</th>
                                    <th>Worker</th>
                                    <th>Task</th>
                                    <th>Status</th>
                                    <th>Due</th>
                                    <th>Start work</th>
                                    <th>End work</th>
                                    <th>Data entry</th>
                                    <th>Complete %</th>
                                  </tr>
                                </thead>
                                <tbody>

                                {% for issues in task_issues %}
                                  <tr>
                                    <td>{{issues.project.name}}</td>
                                    <td>{{issues.user}}</td>
                                    {% if issues.task %}
                                      <td>{{issues.task.name}}</td>
                                    {% else %}
                                      <td>-----</td>
                                    {% endif %}
                                    <td>{{issues.status}}</td>
                                    <td>{{issues.due}}</td>
                                    <td>{{issues.today_start_work}}</td>
                                    <td>{{issues.today_end_work}}</td>
                                    <td>{{issues.total_data_entry_today}}</td>
                                    <td>{{issues.complete_per}}%</td>
                                  </tr>
                                {% endfor %} 

                                </tbody>
                                
                              </table>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                    


                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid Ends-->
  </div>
</div>

{% endblock body %}
    