leader/urls.py
from django.urls import path
from leader import views

app_name = 'leader'
urlpatterns = [
    path('dashboard/', views.LeaderDashboardAPIView.as_view(), name='leader_dashboard'),
    path('dashboard/worker/', views.WorkerListTemplateAPIView.as_view(), name='leader_worker'),
    path('dashboard/project/', views.ProjectListTemplateAPIView.as_view(), name='leader_project'),
    path('dashboard/project/<str:pk>/', views.ProjectDetailTemplateAPIView.as_view(), name='leader_project_detail'),
    path('dashboard/project/add/new/', views.ProjectCreateTemplateAPIView.as_view(), name='leader_project_add'),
    path('dashboard/project/submited/list/', views.SubmitedProjectsTemplateAPIView.as_view(), name='leader_project_submission'),
    path('dashboard/task/', views.TaskListTemplateAPIView.as_view(), name='leader_task'),
    path('dashboard/notification/send/', views.SendNotificationTemplateView.as_view(), name='leader_send_notification'),
]

project_management/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('main/admin/', admin.site.urls),
    path('', include('accounts.urls', namespace='accounts')),
    path('leader/', include('leader.urls', namespace='leader')),
    path('worker/', include('worker.urls', namespace='worker')),
    path('admin/', include('admin_dashboard.urls', namespace='admin_dashboard')),
    path('payments/', include('payments.urls', namespace='payments')),
]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

worker/urls.py
import imp
from django.urls import path
from worker import views

app_name = 'worker'

urlpatterns = [
    path('dashboard/', views.WorkerDashboardTemplateAPIView.as_view(), name='worker_dashboard'),
    path('dashboard/project/', views.ProjectListTemplateView.as_view(), name='worker_project'),
    path('dashboard/project/<str:pk>/', views.ProjectDetailTemplateView.as_view(), name='worker_project_detail'),
    path('dashboard/task/', views.TaskListTemplateView.as_view(), name='worker_task'),
    path('dashboard/project/submited/list/', views.SubmitedProjectsTemplateView.as_view(), name='worker_project_submited'),
    path('dashboard/project/payment/accept/<str:pk>/', views.AcceptProjectTemplateView.as_view(), name='worker_project_accept'),
    path('dashboard/payments/info/', views.MyPaymentsTemplateView.as_view(), name='worker_my_payment'),
]

leader/models.py
from django.db import models

# Create your models here.

projects/forms.py
from django import forms
from projects.models import Categories, Project, Task, Issues, ProjectSubmission
from django.contrib.auth import get_user_model

User = get_user_model()

class ProjectModelForm(forms.ModelForm):
    worker = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(user_type='worker'),
        widget=forms.CheckboxSelectMultiple
    )
    class Meta:
        model = Project
        fields = [
            'name',
            'category',
            'worker',
            'status',
            'work_start_date',
            'work_end_date',
            'deadline',
            'project_client_budget',
            'project_eastemate_cost',
            'sort_description',
            'description',
            'complete_per',
            'file',
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Project name *'}),
            'category': forms.Select(attrs={'class': 'form-select'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'work_start_date': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en'}),
            'work_end_date': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en'}),
            'deadline': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en'}),
            'project_client_budget': forms.NumberInput(attrs={'class': 'form-control'}),
            'project_eastemate_cost': forms.NumberInput(attrs={'class': 'form-control'}),
            'sort_description': forms.TextInput(attrs={'class': 'form-control', 'id': 'exampleFormControlTextarea4', 'rows':'3'}),
            
        }


class TaskModelForm(forms.ModelForm):
    worker = forms.ModelMultipleChoiceField(
        queryset=User.objects.filter(user_type='worker'),
        widget=forms.CheckboxSelectMultiple
    )
    class Meta:
        model = Task
        fields = [
            'name',
            'project',
            'worker',
            'status',
            'due',
            'deadline',
            'is_active',
            'complete_per',
            'description',
            'file'
        ]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'project': forms.Select(attrs={'class': 'form-select'}),
            'status': forms.Select(attrs={'class': 'form-select'}),
            'due': forms.Select(attrs={'class': 'form-select'}),
            'deadline': forms.DateInput(attrs={'class': 'form-select datepicker-here', 'data-language':'en', 'placeholder': 'Date'}),
            'is_active': forms.CheckboxInput(attrs={'class': 'checkbox_animated', 'type': 'checkbox'}),
            'complete_per': forms.TextInput(attrs={'class': 'form-control'})
            
        }


# Project submission 
class ProjectSubmissionModelForm(forms.ModelForm):
    class Meta:
        model = ProjectSubmission
        fields = ['project', 'description', 'file']


class IssuesModelForm(forms.ModelForm):
    class Meta:
        model = Issues
        fields = [
            'status',
            'due',
            'today_start_work',
            'today_end_work',
            'total_data_entry_today',
            'complete_per',
            'file'
        ]
        widgets = {
            'status': forms.Select(attrs={'class': 'form-select'}),
            'due': forms.Select(attrs={'class': 'form-select'}),
            'today_start_work': forms.TimeInput(attrs={'class': 'form-select', 'type':'time'}),
            'today_end_work': forms.TimeInput(attrs={'class': 'form-select', 'type':'time'}),
            'total_data_entry_today': forms.TextInput(attrs={'class': 'form-control'}),
            'complete_per': forms.NumberInput(attrs={'class': 'form-control'})
            
        }

leader/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.urls import reverse
from django.db.models import Q
from django.contrib import messages
from django.views.generic import TemplateView
from django.contrib.auth import get_user_model
from projects.models import Categories, Project, Task, Issues, ProjectSubmission
from projects.forms import ProjectModelForm, TaskModelForm, ProjectSubmissionModelForm, IssuesModelForm
from accounts.forms import RegisterForm, NotificationForm

User = get_user_model()

# leader dashboard index view
class LeaderDashboardAPIView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # admin access
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')

            # leader access
            elif request.user.user_type == 'leader':
                if request.user.profile.is_fully_filled():
                    # count area
                    worker_count = User.objects.filter(user_type = 'worker').count()
                    projects_count = Project.objects.filter(Q(leader=request.user) & Q(is_active = True)).count()
                    tasks_count = Task.objects.filter(is_active = True).count()
                    submission_task_count = '0'

                    # object filter area
                    ongoing_projects = Project.objects.filter(Q(leader=request.user) & Q(is_active = True)).order_by('-id')

                    context = {
                        'worker_count': worker_count,
                        'projects_count': projects_count,
                        'tasks_count': tasks_count,
                        'submission_task_count': submission_task_count,
                        'ongoing_projects': ongoing_projects
                    }
                    return render(request, 'leader/index.html', context)
                else:
                    return redirect('accounts:accounts_edit_profile')
            
            # worker access
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        pass

# worker creation and list view
class WorkerListTemplateAPIView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # admin access
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')

            # leader access
            elif request.user.user_type == 'leader':
                workers = User.objects.filter(user_type='worker').order_by('-id')
                context = {
                    'workers': workers
                }
                return render(request, 'leader/workers.html', context)
            
            # worker access
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # admin access
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            # leader access
            elif request.user.user_type == 'leader':
                email = request.POST.get('email')
                password1 = request.POST.get('password1')
                password2 = request.POST.get('password2')
                formData = {
                    'email': email,
                    'password1': password1,
                    'password2': password2
                }
                form = RegisterForm(formData)
                
                if form.is_valid():
                    instance = form.save(commit=False)
                    instance.user_type = 'worker'
                    instance.is_active = True
                    instance.save()
                    return redirect('leader:leader_worker')
                
                context = {
                    
                }
                return render(request, 'leader/new_worker.html', context)
            # worker access
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        
        else:
            return redirect('accounts:login')

# project List view
class ProjectListTemplateAPIView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # redirect to user dashboard
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            elif request.user.user_type == 'leader':
                projects = Project.objects.filter(Q(leader=request.user) & Q(is_active = True)).order_by('-id')
                context = {
                    'projects': projects
                }
                return render(request, 'leader/projects.html', context)
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        pass

# project detials view
class ProjectDetailTemplateAPIView(TemplateView):
    def get(self, request, pk, *args, **kwargs):
        if request.user.is_authenticated:
            # redirect to user dashboard
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            elif request.user.user_type == 'leader':
                project = Project.objects.get(id=pk)
                tasks = Task.objects.filter(project=project).order_by('-id')

                form = ProjectSubmissionModelForm()
                issues_form = IssuesModelForm()
                
                context = {
                    'project': project,
                    'tasks': tasks,
                    'form': form,
                    'issues_form': issues_form
                }
                return render(request, 'leader/project_detail.html', context)
            elif request.user.user_type == 'worker':
                return redirect('worker:worker_dashboard')
            else:
                return redirect('accounts:login')
        else:
            return redirect('accounts:login')

    def post(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            if request.method == 'post' or request.method == 'POST':
                # here will execude tasks
                project_id = request.POST.get('project_id')
                project_obj = Project.objects.get(id=project_id)
                postData = {
                    'project': project_obj,
                    'description': request.POST.get('description'),
                    'file': request.POST.get('file')
                }
                form = ProjectSubmissionModelForm(postData, request.FILES)
                # Issues form submission ======================================
                issues_form = IssuesModelForm(request.POST, request.FILES)

                # Project form submission ======================================
                if form.is_valid():
                    if ProjectSubmission.objects.filter(project=project_id).exists():
                        messages.info(request, "This Project Has Been Submited..!")
                        return redirect('leader:leader_project')
                    else:
                        instance = form.save(commit=False)
                        instance.user = request.user
                        instance.status = 'done'
                        ## here will update all {project, task} status to DONE becouse project is submited
                        project_obj.status = 'done'
                        project_obj.complete_per = 100
                        for task in project_obj.tasks.all():
                            task.status = 'done'
                            task.due = 'done'
                            task.save()
                        project_obj.save()
                        ## end updated all info
                        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))

                # Issues form submission ======================================
                if issues_form.is_valid():
                    instance = issues_form.save(commit=False)
                    instance.project = project_obj
                    instance.task = None
                    instance.is_active = True
                    instance.save()
                    return redirect('leader:leader_project')
                
                else:
                    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
                
                
            
            else:
                return HttpResponseRedirect(request.META.get('HTTP_REFERER')) # return the same page if run this (else) conditon

        else:
            return redirect('accounts:login')

# project creation view
class ProjectCreateTemplateAPIView(TemplateView):
    def get(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            # redirect to user dashboard
            if request.user.user_type == 'admin':
                return redirect('admin_dashboard:admin_dashboard')
            elif request.user.user_type == 'leader':
                form = ProjectModelForm()
                context = {
                    'form': form

projects/views.py
from django.shortcuts import render

from django.views.generic import TemplateView

leader/templates/leader/project_submission.html
{% extends "base.html" %}
{% block title %}Submited Projects Data{% endblock title %}
{% load project_data_entry %}

{% block body %}

<!-- Page Body Start-->
<div class="page-body-wrapper">
  <!-- Page Sidebar Start-->

  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>Submited Projects</h3>
          </div>
          <div class="col-12 col-sm-6">
            <ol class="breadcrumb">
              <li class="breadcrumb-item"><a href="index.html">                                       <i data-feather="home"></i></a></li>
              <li class="breadcrumb-item">project</li>
              <li class="breadcrumb-item active">submited</li>
              <li class="breadcrumb-item active">list</li>
            </ol>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="row">

        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="table-responsive">
                <table class="display" id="advance-1">
                  <thead>
                    <tr>
                      <th>Name</th>
                      <th>Submit By</th>
                      <th>Status</th>
                      <th>Data Entry</th>
                      <th>Start Work</th>
                      <th>End Work</th>
                      <th>Budget</th>
                    </tr>
                  </thead>
                  <tbody>
                    {% for project in submited_projects %}
                      <tr>
                        <td>{{project.project.name}}</td>
                        <td>{{project.user}}</td>
                        <td>{{project.project.status}}</td>
                        <td>{{project.project | total_data_entry}}</td>
                        <td>{{project.project.work_start_date}}</td>
                        <td>{{project.project.work_end_date}}</td>
                        <td>{{project.project.project_client_budget}}</td>
                      </tr>
                    {% endfor %}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>


      </div>
    </div>
    <!-- Container-fluid Ends-->
  </div>
</div>

{% endblock body %}
    

leader/templates/leader/projects.html
{% extends 'base.html' %}
{% block title %}Projects List{% endblock title %}
{% block body %}
 <!-- Page Body Start-->
 <div class="page-body-wrapper default-menu default-menu">
  <!-- Page Sidebar Start-->
  
  {% include 'sidebar.html' %}

  <!-- Page Sidebar Ends-->
  <div class="page-body">
    <div class="container-fluid">
      <div class="page-title">
        <div class="row">
          <div class="col-12 col-sm-6">
            <h3>
               Project List</h3>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid starts-->
    <div class="container-fluid">
      <div class="row project-cards">
        <div class="col-md-12 project-list">
          <div class="card">
            <div class="row">
              <div class="col-md-6 p-0">
                <ul class="nav nav-tabs border-tab" id="top-tab" role="tablist">
                  <li class="nav-item"><a class="nav-link" id="profile-top-tab" data-bs-toggle="tab" href="#top-stuck" role="tab" aria-controls="top-stuck" aria-selected="false"><i data-feather="info"></i>Stuck</a></li>
                  <li class="nav-item"><a class="nav-link" id="contact-top-tab" data-bs-toggle="tab" href="#top-working" role="tab" aria-controls="top-working" aria-selected="false"><i data-feather="check-circle"></i>Working</a></li>
                  <li class="nav-item"><a class="nav-link" id="contact-top-tab" data-bs-toggle="tab" href="#top-done" role="tab" aria-controls="top-done" aria-selected="false"><i data-feather="check-circle"></i>Done</a></li>
                </ul>
              </div>
              <div class="col-md-6 p-0">                    
                <div class="form-group mb-0 me-0"></div><a class="btn btn-primary" href="{% url 'leader:leader_project_add' %}"> <i data-feather="plus-square"> </i>Create New Project</a>
              </div>
            </div>
          </div>
        </div>
        <div class="col-sm-12">
          <div class="card">
            <div class="card-body">
              <div class="tab-content" id="top-tabContent">

              
                <div class="tab-pane fade show active" id="top-stuck" role="tabpanel" aria-labelledby="top-home-tab">
                  <div class="row">

                    {% for project in projects %}
                      {% if project.status == 'stuck' %}
                        <div class="col-xxl-4 box-col-6 col-lg-6">
                          <div class="project-box"><span class="badge badge-primary">{{project.status}}</span>
                            <a href="{% url 'leader:leader_project_detail' pk=project.id %}"><h6>{{project.name}}</h6></a>
                            <div class="media"><img class="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="" data-original-title="" title="">
                              <div class="media-body">
                                <p>{{project.category}}</p>
                              </div>
                            </div>
                            <p>{{project.sort_description|truncatechars:50}}</p>
                            <div class="row details">
                              <div class="col-6"><span>Issues </span></div>
                              <div class="col-6 font-primary">{{project.issues.count}} </div>
                              <div class="col-6"> <span>Tasks</span></div>
                              <div class="col-6 font-primary">{{project.tasks.count}}</div>
                            </div>
                            <div class="customers">
                              <ul>
                                {% for worker in project.worker.all %}
                                  {% if worker.employe_image %}
                                    <li class="d-inline-block"><img class="img-30 rounded-circle" src="{{worker.profile.employe_image.url}}" alt="" data-original-title="" title=""></li>
                                  {% else %}
                                  <li class="d-inline-block"><img class="img-30 rounded-circle" src="https://acce.edu.au/wp-content/uploads/2018/09/placeholder-profile-sq.jpg" alt="" data-original-title="" title=""></li>
                                  {% endif %}
                                  {% endfor %}
                                <li class="d-inline-block ms-2">
                                  <p class="f-12">+{{project.worker.count}} More</p>
                                </li>
                              </ul>
                            </div>
                            <div class="project-status mt-4">
                              <div class="media mb-0">
                                <p>{{project.complete_per}}% </p>
                                <div class="media-body text-end"><span>Done</span></div>
                              </div>
                              <div class="progress" style="height: 5px">
                                <div class="progress-bar-animated bg-primary progress-bar-striped" role="progressbar" style="width: {{project.complete_per}}%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                    {% endfor %}

                  </div>
                </div>

                <div class="tab-pane fade" id="top-working" role="tabpanel" aria-labelledby="top-home-tab">
                  <div class="row">

                    {% for project in projects %}
                      {% if project.status == 'working' %}
                        <div class="col-xxl-4 box-col-6 col-lg-6">
                          <div class="project-box"><span class="badge badge-primary">{{project.status}}</span>
                            <a href="{% url 'leader:leader_project_detail' pk=project.id %}"><h6>{{project.name}}</h6></a>
                            <div class="media"><img class="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="" data-original-title="" title="">
                              <div class="media-body">
                                <p>{{project.category}}</p>
                              </div>
                            </div>
                            <p>{{project.sort_description|truncatechars:50}}</p>
                            <div class="row details">
                              <div class="col-6"><span>Issues </span></div>
                              <div class="col-6 font-primary">{{project.issues.count}} </div>
                              <div class="col-6"> <span>Tasks</span></div>
                              <div class="col-6 font-primary">{{project.tasks.count}}</div>
                            </div>
                            <div class="customers">
                              <ul>
                                {% for worker in project.worker.all %}
                                  {% if worker.employe_image %}
                                    <li class="d-inline-block"><img class="img-30 rounded-circle" src="{{worker.profile.employe_image.url}}" alt="" data-original-title="" title=""></li>
                                  {% else %}
                                  <li class="d-inline-block"><img class="img-30 rounded-circle" src="https://acce.edu.au/wp-content/uploads/2018/09/placeholder-profile-sq.jpg" alt="" data-original-title="" title=""></li>
                                  {% endif %}
                                  {% endfor %}
                                <li class="d-inline-block ms-2">
                                  <p class="f-12">+{{project.worker.count}} More</p>
                                </li>
                              </ul>
                            </div>
                            <div class="project-status mt-4">
                              <div class="media mb-0">
                                <p>{{project.complete_per}}% </p>
                                <div class="media-body text-end"><span>Done</span></div>
                              </div>
                              <div class="progress" style="height: 5px">
                                <div class="progress-bar-animated bg-primary progress-bar-striped" role="progressbar" style="width: {{project.complete_per}}%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                    {% endfor %}

                  </div>
                </div>

                <div class="tab-pane fade" id="top-done" role="tabpanel" aria-labelledby="top-home-tab">
                  <div class="row">

                    {% for project in projects %}
                      {% if project.status == 'done' %}
                        <div class="col-xxl-4 box-col-6 col-lg-6">
                          <div class="project-box"><span class="badge badge-primary">{{project.status}}</span>
                            <a href="{% url 'leader:leader_project_detail' pk=project.id %}"><h6>{{project.name}}</h6></a>
                            <div class="media"><img class="img-20 me-2 rounded-circle" src="../assets/images/user/3.jpg" alt="" data-original-title="" title="">
                              <div class="media-body">
                                <p>{{project.category}}</p>
                              </div>
                            </div>
                            <p>{{project.sort_description|truncatechars:50}}</p>
                            <div class="row details">
                              <div class="col-6"><span>Issues </span></div>
                              <div class="col-6 font-primary">{{project.issues.count}} </div>
                              <div class="col-6"> <span>Tasks</span></div>
                              <div class="col-6 font-primary">{{project.tasks.count}}</div>
                            </div>
                            <div class="customers">
                              <ul>
                                {% for worker in project.worker.all %}
                                  {% if worker.employe_image %}
                                    <li class="d-inline-block"><img class="img-30 rounded-circle" src="{{worker.profile.employe_image.url}}" alt="" data-original-title="" title=""></li>
                                  {% else %}
                                  <li class="d-inline-block"><img class="img-30 rounded-circle" src="https://acce.edu.au/wp-content/uploads/2018/09/placeholder-profile-sq.jpg" alt="" data-original-title="" title=""></li>
                                  {% endif %}
                                  {% endfor %}
                                <li class="d-inline-block ms-2">
                                  <p class="f-12">+{{project.worker.count}} More</p>
                                </li>
                              </ul>
                            </div>
                            <div class="project-status mt-4">
                              <div class="media mb-0">
                                <p>{{project.complete_per}}% </p>
                                <div class="media-body text-end"><span>Done</span></div>
                              </div>
                              <div class="progress" style="height: 5px">
                                <div class="progress-bar-animated bg-primary progress-bar-striped" role="progressbar" style="width: {{project.complete_per}}%" aria-valuenow="10" aria-valuemin="0" aria-valuemax="100"></div>
                              </div>
                            </div>
                          </div>
                        </div>
                      {% endif %}
                    {% endfor %}

                  </div>
                </div>
                


              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    <!-- Container-fluid Ends-->
  </div>
</div>
{% endblock body %}
 